feat: force .bcup extension for new vault
buttercup/buttercup-desktop pull request #954
Opened 2020-10-11 16:10 UTC by antoine-amara

when creating a new vault the user enter a name. Be sure to force the
new vault name with .bcup extension to be able to finalize the
archive creation (open the archive and create a password).

Fixes: https://github.com/buttercup/buttercup-desktop/issues/860

2020-10-12 19:06 UTC, perry-mitchell requested changes

2020-10-12 19:06 UTC, perry-mitchell commented on src/main/lib/files.js
> +      path: normalizePath(filePath + '.bcup')
This rewrite of `payload` isn't needed, it would be fine to just set `path`, leaving the definition as `const`.

2020-10-14 11:30 UTC, antoine-amara commented
Thanks for the review @perry-mitchell , I push the changes.

2020-10-19 17:24 UTC, antoine-amara commented
Hello @perry-mitchell , please take a look at the changes when you have a chance :)

2020-10-20 19:27 UTC, perry-mitchell approved these changes

2020-10-20 22:37 UTC, sallar approved these changes

2021-02-20 12:34 UTC, perry-mitchell approved these changes

2021-02-20 12:34 UTC, merged