show vault's title on password modal
buttercup/buttercup-desktop pull request #956
Opened 2020-10-25 18:31 UTC by antoine-amara

## Description

when opening an archive (on the sidebar), pass the item to active to
show to the user the selected item. Pass the archive name to the
password modal to display the archive name.
manage the selected archive from modalRequest state from the workspace and
pass the info to the sidebar to make it active. retrieve and pass the
name to the password modal to be able to display the archive name.

Fixes: #812

## Screenshot

![password-name](https://user-images.githubusercontent.com/10661789/97115726-93110a00-16f8-11eb-8a5a-78ebe4875836.png)

2020-10-28 19:12 UTC, perry-mitchell requested changes
Could we move the name up a little bit? It looks a touch too far away from the top border, vertically.

2020-10-28 19:13 UTC, perry-mitchell commented
This is very helpful! We'll be releasing a new UI shortly, so this might undergo some changes, but this would be great to get out in the meantime.

2020-10-31 16:51 UTC, antoine-amara commented
Thanks @perry-mitchell , I push somes changes:
- I resolve a mistake on my code when trying to retrieve the archive name
- I reduce the margin between the archive name and the top of the dialog box.

2020-11-19 20:19 UTC, perry-mitchell approved these changes

2021-02-20 12:35 UTC, perry-mitchell approved these changes

2021-02-20 12:35 UTC, merged